produto/urls.py
from django.urls import path
from produto import views

app_name = 'produto'

urlpatterns = [
    path('', views.index, name='index'),
    path('cadastra_produto/', views.cadastra_produto, name='cadastra_produto'),
    path('lista_produto/', views.lista_produto, name='lista_produto'),
    path('edita_produto/', views.edita_produto, name='edita_produto'),
    path('deleta_produto/', views.deleta_produto, name='deleta_produto'),
   
]

projeto/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import include, path

urlpatterns = [
    path('', lambda request: redirect('produto/')),
    path('produto/', include('produto.urls')),
    path('admin/', admin.site.urls)
]

categoria/models.py
from django.db import models
from django.urls import reverse


class Categoria(models.Model):
    nome = models.CharField(max_length=70, db_index=True, unique=True)
    slug = models.SlugField(max_length=70)

    class Meta:
        db_table='categoria'
        ordering = ('nome',)

    def __str__(self):
        return self.nome

    def get_absolute_url(self):
        return reverse('carrinho:lista_produtos_por_categoria', args=[self.slug])

produto/models.py
from django.db import models
from django.urls import reverse

from categoria.models import Categoria

class Produto(models.Model):
    categoria = models.ForeignKey(Categoria, related_name='produtos', on_delete=models.DO_NOTHING)
    nome = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100)
    quantidade = models.IntegerField()
    preco = models.DecimalField(max_digits=5, decimal_places=2)

    class Meta:
        db_table='produto'

    def __str__(self):
        return self.nome

    def get_absolute_url(self):
        return reverse('carrinho:exibe_produto', args=[self.id, self.slug])

produto/forms.py
from django import forms
from django.core.validators import RegexValidator

from categoria.models import Categoria
from produto.models import Produto
from trabalho6 import settings


class PesquisaProdutoForm(forms.Form):

    nome = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control form-control-sm', 'maxlength': '100'}),
        required=False)



class ProdutoForm(forms.ModelForm):

    class Meta:
        model = Produto
        fields = ('nome', 'categoria', 'preco', 'quantidade',)
        localized_fields = ('preco',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['nome'].error_messages={'required': 'Campo obrigatório.'}
        self.fields['nome'].widget.attrs.update({'class': 'form-control form-control-sm'})

        self.fields['categoria'].error_messages={'required': 'Campo obrigatório'}
        self.fields['categoria'].queryset=Categoria.objects.all().order_by('nome')
        self.fields['categoria'].empty_label='--- Selecione uma categoria ---'
        self.fields['categoria'].widget.attrs.update({'class': 'form-control form-control-sm'})


        self.fields['preco'].min_value=0
        self.fields['preco'].error_messages={'required': 'Campo obrigatório.',
                                             'invalid': 'Valor inválido.',
                                             'max_digits': 'Mais de 5 dígitos no total.',
                                             'max_decimal_places': 'Mais de 2 dígitos decimais.',
                                             'max_whole_digits': 'Mais de 3 dígitos inteiros.'}
        self.fields['preco'].widget.attrs.update({
            'class': 'form-control form-control-sm',
            'onkeypress': 'return (event.charCode >= 48 && event.charCode <= 57) || event.charCode == 44'
        })

        self.fields['quantidade'].min_value=0
        self.fields['quantidade'].error_messages={
            'required': 'Campo obrigatório',
            'min_value': 'A quantidade deve ser maior ou igual a zero.'
        }
        self.fields['quantidade'].widget=forms.TextInput(attrs={
            'class': 'form-control form-control-sm',
            'onkeypress': 'return (event.charCode >= 48 && event.charCode <= 57) || event.charCode == 44'
        })




class QuantidadeForm(forms.Form):

    produto_id = forms.CharField(widget=forms.HiddenInput())

    quantidade = forms.IntegerField(
        min_value=0,
        max_value=99,
        widget=forms.TextInput(attrs={'class': 'form-control btn-secondary quantidade border-0',
                                      'style': 'text-align: center; background-color: #6c757d; width: 70px;',
                                      }),
        required=True
    )

categoria/views.py
from django.shortcuts import render

# Create your views here.

produto/views.py
from curses.ascii import HT
from django.contrib import messages
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.forms import model_to_dict
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, get_object_or_404
from django.template.defaultfilters import slugify
from categoria.models import Categoria
from produto.context_processors import atualiza_valor_total
from produto.forms import ProdutoForm, QuantidadeForm
from produto.models import Produto




def index(request):
    return render(request, 'produto/index.html')


def lista_produto(request):
    produtos = Produto.objects.all()

    forms = []
    for produto in produtos:
        form = QuantidadeForm(initial={'quantidade': produto.quantidade, 'produto_id': produto.id})
        forms.append(form)

    return render(request, 'produto/lista_produto.html', {'listas':zip(produtos, forms)})



def cadastra_produto(request):
    if request.POST:
        produto_id = request.session.get('produto_id')
        print('produto_id na sessão = ' + str(produto_id))
        if produto_id:
            produto = get_object_or_404(Produto, pk=produto_id)
            produto_form = ProdutoForm(request.POST, request.FILES, instance=produto)
        else:
            produto_form = ProdutoForm(request.POST, request.FILES)

        if produto_form.is_valid():
            produto = produto_form.save(commit=False)
            produto.slug = slugify(produto.nome)
            produto.save()
            print('produto salvo com sucesso')
            if produto_id:
                messages.add_message(request, messages.INFO, 'Produto alterado com sucesso!')
                del request.session['produto_id']
            else:
                messages.add_message(request, messages.INFO, 'Produto cadastrado com sucesso!')

            print('retornando JSON response')
            return JsonResponse({'produto_id':produto.id,'nome':produto.nome,'preco':produto.preco,'categoria': produto.categoria.nome, 'quantidade': produto.quantidade }, safe=False)
    else:
        try:
            del request.session['produto_id']
        except KeyError:
            pass
        produto_form = ProdutoForm()

    return render(request, 'produto/cadastra_produto.html', {'form': produto_form})


def edita_produto(request):
    if not request.POST:
        return(HttpResponse('Não é POST'))

    form = QuantidadeForm(request.POST)
    if not form.is_valid():
        return(HttpResponse('Formulário inválido'))

    produto_id = form.cleaned_data['produto_id']
    quantidade = form.cleaned_data['quantidade']

    if produto_id:
        produto = get_object_or_404(Produto, pk=produto_id)
        produto.quantidade = quantidade
        produto.save()


       
    return JsonResponse(atualiza_valor_total(request))


def deleta_produto(request):
    if not request.POST:
        return(HttpResponse('Não é POST'))

    form = QuantidadeForm(request.POST)
    if not form.is_valid():
        return(HttpResponse('Formulário inválido'))

    produto_id = form.cleaned_data['produto_id']
    print('produto_id = ' + str(produto_id))
    if produto_id:
        produto = get_object_or_404(Produto, pk=produto_id)
        produto.delete()
        print("produto deletado")

    return JsonResponse(atualiza_valor_total(request))

produto/templates/produto/cadastra_produto.html
{% extends 'base.html' %}

{% load static %}
{% load humanize %}

{% block titulo %}
   Cadastro de Produtos
{% endblock %}

{% block corpo %}
   <div class='mb-4'>
      <h5>Cadastro de Produtos</h5>
      <hr class='mt-0'>
   </div>

   <form action="{% url 'produto:cadastra_produto' %}" method="POST" class="pb-4"
         enctype="multipart/form-data" novalidate>
            <div class="row mb-xl-3">
         <div class="col-xl-6">
            <div class="row">
               <label for="id_categoria" class="col-xl-2 font-weight-bold">Categoria</label>
               <div class="col-xl-10">
                  {{ form.categoria }}
                  {% if form.categoria.errors %}
                     <div class="alert alert-danger mb-0" role="alert" style="padding-top: 2px; padding-bottom: 2px">
                        {% for error in form.categoria.errors %}
                           <small>{{ error }}</small>
                        {% endfor %}
                     </div>
                  {% endif %}
               </div>
            </div>
         </div>
      </div>

      <div class="row mb-xl-3">
         <div class="col-xl-6">
            <div class="row">
               <label for="id_nome" class="col-xl-2 font-weight-bold">Nome</label>
               <div class="col-xl-10">
                  {{ form.nome }}
                  {% if form.nome.errors %}
                     <div class="alert alert-danger mb-0" role="alert" style="padding-top: 2px; padding-bottom: 2px">
                        {% for error in form.nome.errors %}
                           <small>{{ error }}</small>
                        {% endfor %}
                     </div>
                  {% endif %}
               </div>
            </div>
         </div>

      </div>


      <div class="row mb-xl-3">
         <div class="col-xl-6">
            <div class="row">
               <label for="id_quantidade" class="col-xl-2 font-weight-bold">Quantidade</label>
               <div class="col-xl-10">
                  {{ form.quantidade }}
                  {% if form.quantidade.errors %}
                     <div class="alert alert-danger mb-0" role="alert" style="padding-top: 2px; padding-bottom: 2px">
                        {% for error in form.quantidade.errors %}
                           <small>{{ error }}</small>
                        {% endfor %}
                     </div>
                  {% endif %}
               </div>
            </div>
         </div>

      </div>

      <div class="row mb-3">
          <div class="col-xl-6">
            <div class="row">
               <label for="id_preco" class="col-xl-2 font-weight-bold">Preço</label>
               <div class="col-xl-10">
                  {{ form.preco }}
                  {% if form.preco.errors %}
                     <div class="alert alert-danger mb-0" role="alert" style="padding-top: 2px; padding-bottom: 2px">
                        {% for error in form.preco.errors %}
                           <small>{{ error }}</small>
                        {% endfor %}
                     </div>
                  {% endif %}
               </div>
            </div>
         </div>
      </div>

      <div class="row mb-5">
         <div class="col-xl-6">
            <div class="row">
               <div class="col-xl-10 offset-xl-2">
                  {% csrf_token %}
                  <button id="botao" type="button" class="btn btn-primary cadastrar_produto">
                        <img src="{% static 'images/skin/database_add.png' %}"> Cadastrar
                  </button>
               </div>
            </div>
         </div>
      </div>

   </form>

   
   
   {% endblock %}
   
 
     
         {% block domready %}

      

            const criarNovaLinha = (response, penultimo_tr) => {
               let novo_tr = penultimo_tr.clone()
               let novo_tr_nome = novo_tr.find(".produto_nome").text(response.nome)
               let novo_tr_categoria = novo_tr.find(".produto_categoria").text(response.categoria)
               let novo_tr_preco = novo_tr.find(".produto_preco").text("").append("R$ ").append(response.preco)
               let novo_tr_input_id = novo_tr.find("#id_produto_id").val(response.id)
               let novo_tr_quantidade = novo_tr.find("#id_quantidade").val(response.quantidade)

               
               penultimo_tr.after(novo_tr)
            }
            
         
            $('#botao').click( function(){
               const form = $(this).closest('form')
               const url = form.attr('action')
               const formData = form.serializeArray()
               const penultimo_tr = $('.table tr:last').prev()

               $.post(url, formData, function(response){
                  console.log(response)
                  criarNovaLinha(response, penultimo_tr)
                  
               })
            })
   
   
         {% endblock %}
 

produto/templates/produto/index.html
{% extends 'base.html' %}

{% load static %}

{% block titulo %}
    Venda de Produtos
{% endblock %}

{% block corpo %}
    <br>
        <div id="form">

        </div>
    <br>
        <div id="tabela">

        </div>
    <br/>
    <br/>
    <br/>
{% endblock %}


 

{%block domready%}   
$(document).ready(function(){

    
        $.ajax({
            url: '{% url "produto:cadastra_produto" %}',
            type: 'GET',
            dataType: 'html',
            success: function(data){
                $('#form').html(data);
            }
        });

        $.ajax({
            url: '{% url "produto:lista_produto" %}',
            type: 'GET',
            dataType: 'html',
            success: function(data){
                $('#tabela').html(data);
            }
        });



    });
    
    


    
{%endblock%}

produto/templates/produto/lista_produto.html
{% extends "base.html" %}

{% load static %}
{% load humanize %}


{% block corpo %}

   <div id="tabela">
      <div class="mt-3 mb-4">
         <h5 class="mb-2 text-primary">Lista de Produtos</h5>
      </div>

      <div class="table-responsive mb-3">
         <table class="table table-sm" id="tabela">
            <colgroup>
               <col width="40%">
               <col width="15%">
               <col width="15%">
               <col width="15%">
               <col width="15%">
            </colgroup>
            <thead>
               <tr>
                  <th class="text-center">Nome</th>
                  <th class="text-center">Categoria</th>
                  <th class="text-center">Quantidade</th>
                  <th class="text-center">Preço</th>
                  <th class="text-center">Remover</th>
               </tr>
            </thead>
            <tbody>
               {% for produtos, form in listas %}
                  <tr>
                     <td class="text-left align-middle">
                        <div class="media">
                           <div class="media-body">
                              <h6 class="mt-2">
                                 <a class="produto_nome" style="text-decoration: none" href="{{ produtos.produto.get_absolute_url }}"
                                    tabindex="-1">
                                    {{ produtos.nome}}
                                 </a>
                              </h6>
                           </div>
                        </div>
                     </td>

                     <td class="text-center align-middle produto_categoria">
                        {{ produtos.categoria }}

                     </td>

                     <td class="text-center align-middle">
                        <form class="mx-auto" style="width: 60px;"
                        action="{% url 'produto:edita_produto' %}"
                              method ="POST" novalidate>
                           {% csrf_token %}
                           {{ form.produto_id }}
                           {{ form.quantidade }}
                        </form>
                     </td>

                     <td class="text-right pr-5 align-middle produto_preco">
                        R$ {{ produtos.preco | intcomma }}
                     </td>

                     <td class="text-center align-middle">
                        <form 
                              action="{% url 'produto:deleta_produto' %}"
                              method ="post" novalidate>
                           {% csrf_token %}
                           {{ form.produto_id }}
                           <button style="margin-top: 0px; margin-bottom: 0px;
                                          padding-top: 3px; padding-bottom: 3px;
                                          width: 40px"
                                   type="button"
                                   class="btn btn-sm btn-danger remover"
                                   tabindex="-1">
                              <img src="{% static 'images/skin/remove.png' %}">
                           </button>
                        </form>
                     </td>
                     
                  </tr>
               {% endfor %}
               <tr>
                  <td colspan="3">
                     <strong style="margin-left: 10px">Total do carrinho ...</strong>
                  </td>
                  <td class="text-right pr-5">
                     <strong>R$</strong><strong id="valor-do-carrinho">{{ valor_total | floatformat:2 | intcomma }}</strong>
                  </td>
                  <td></td>
               </tr>
            </tbody>
         </table>
      </div>
   </div>

{% endblock %}

{% block domready %}

   $('#tabela').on('blur', "input.quantidade", function(){
      const nova_quantidade = $(this).val()

      const form = $(this).closest('form')
      const url = form.attr('action')
      const formData = form.serializeArray()

      $.post(url, formData, function(response){
         console.log(response)
         $('#valor-do-carrinho').text(response.valor_total)
      })

   })


   $('#tabela').on('click', ".remover", function(){
      const form = $(this).closest('form')
      form.append('<input type="hidden" name="quantidade" value="0">')
      const url = form.attr('action')
      const formData = form.serializeArray()
      const tr = $(this).closest('tr')

      $.post(url, formData, function(response){
         console.log(response)
         $('#valor-do-carrinho').text(response.valor_total)
         tr.fadeTo(500, 0, function(){
            tr.remove()
         })

      })

   })

{% endblock %}

templates/base.html
{% load static %}
{% load humanize %}


<!Doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/jquery-ui.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}" />
    <title>{% block titulo %}Hortifruti{% endblock %}</title>
    <style>
        {% block estilo %}

        {% endblock %}
    </style>
</head>
<body class="barra">



    <div style="padding: 3px" class="bg-danger mb-3"></div>

    <div id="container" class="container">
        {% block corpo %}

        {% endblock %}
    </div>

   

    <script src="{% static 'js/jquery-3.4.1.js' %}"></script>
    <script src="{% static 'js/jquery-ui.min.js' %}"></script>
    <script src="{% static 'js/jquery.mask.js' %}"></script>
    <script src="{% static 'js/popper.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/script.js' %}"></script>

    <script>
        $(document).ready(function(){

            {% block domready %}

             

            {% endblock %}
        });
    </script>




</body>
</html>